kind: Module
name: hello
description: Greeting service
type: container
services:
  - name: hello
    args: [npm, start]
    ports:
      - name: http
        containerPort: 8080
    ingresses:
      - path: /hello
        port: http
    dependencies:
      - node-migration
tests:
  - name: unit
    args: [npm, test]
tasks:
  - name: node-migration
    args: [knex, migrate:latest]
    description: Creates the users table.
    dependencies:
      - postgres
  - name: foo-task
    args: [echo, hello]
