apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "docker-daemon.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "docker-daemon.name" . }}
    helm.sh/chart: {{ include "docker-daemon.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "docker-daemon.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "docker-daemon.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      strategy:
        # We only want one instance at a time, because we're using the same volume for the data
        type: Recreate
      volumes:
        - name: docker-data
          persistentVolumeClaim:
            claimName: docker-data
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: docker
              containerPort: 2375
              protocol: TCP
          securityContext:
            privileged: true
          livenessProbe:
            tcpSocket:
              port: 2375
          readinessProbe:
            tcpSocket:
              port: 2375
          volumeMounts:
            - mountPath: /var/lib/docker
              name: docker-data
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
